{
 "title": "FastapiAppDashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration change / min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests / min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "increase(main_app_predictions_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of high evaluations (price > 10.000.000)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "main_app_counter_pos_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}